name: deploy-model-training-pipeline

on:
  push:
    branches:
      - spam-detection
  workflow_dispatch:

jobs:
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml

  register-environment:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      environment_file: mlops/azureml/train/train-env.yml
      conda_file: data-science/environment/train-conda.yml
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
          
  register-dataset:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: taxi-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
      
  verify-compute:
    needs: [get-config, register-environment, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Install Azure ML extension
        run: |
          az extension add --name ml
          az extension list

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Compute Cluster
        run: |
          echo "Verifying pre-created compute cluster: cpu-cluster"
          az ml compute show --name cpu-cluster --resource-group ${{ needs.get-config.outputs.resource_group }} --workspace-name ${{ needs.get-config.outputs.aml_workspace }}

  run-pipeline:
    needs: [get-config, register-environment, verify-compute, register-dataset]
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/azureml/train/pipeline.yml
      job-name: test
    secrets:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
